apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  labels:
    app: heart-disease-predictor
spec:
  type: LoadBalancer
  selector:
    app: heart-disease-predictor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
